# Generated by Django 6.0.6 on 2026-06-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('USD', '$ US Dollar'), ('INR', '₹ Indian Rupee'), ('EUR', '€ Euro'), ('GBP', '£ British Pound')], default='USD', max_length=10),
        ),
    ]
